Forms layouts 2
LeksoKashia/Budgetify pull request #5
Opened 2024-02-28 13:03 UTC by LeksoKashia

Implemented piggy bank, card activation, subscription and obligatory layouts

2024-02-28 17:50 UTC, akarmilchik requested changes
Good progress, a lot of thins made, cool!

Just need to fix comments and do a refactoring in several places.

2024-02-28 17:50 UTC, akarmilchik commented on src/app/components/user-actions/user-actions.component.ts
> +    setTimeout(() => {
Please remove setTimeout() calls. It is not good to use them just for updating data. You should use reactive approach, maybe you can use Observables or Subjects.

2024-02-28 17:50 UTC, akarmilchik commented on src/app/components/accounts/accounts.component.ts
> +    setTimeout(() => {
Please remove setTimeout() calls. It is not good to use them just for updating data. You should use reactive approach, maybe you can use Observables or Subjects.

2024-02-28 17:50 UTC, akarmilchik commented on src/app/components/accounts/accounts.component.ts
> +      this.activeCardId = activeCard.id;
It's not a good approach to create a new variable just for use it once.
You can do it like that: 
```suggestion
      this.activeCardId = JSON.parse(storedCard).id;
```

2024-02-28 17:50 UTC, akarmilchik commented on src/app/components/admin/admin.component.ts
> +          if (!c.isActive) {
Instead of **c**, please give a proper name for card variable inside the forEach function

2024-02-28 17:50 UTC, akarmilchik commented on src/app/components/forms/add/add-money-to-piggy/add-money-to-piggy.component.ts
> +    if (this.piggyForm.valid) {
Please avoid unnecessary nesting with IF's.
It is better to check a negative scenario, than continue just with your logic:
```suggestion
    if (!this.piggyForm.valid) {
        return;
    }
```

2024-02-28 17:50 UTC, akarmilchik commented on src/app/components/forms/edit/piggy-bank-edit/piggy-bank-edit.component.ts
> +  }
To add empty line

2024-02-28 17:50 UTC, akarmilchik commented on src/app/components/forms/edit/piggy-bank-edit/piggy-bank-edit.component.ts
> +    if (this.piggyForm.valid) {
The same proposal is about IF nesting, Please use a negative scenario check here

2024-02-28 17:50 UTC, akarmilchik commented on src/app/components/forms/info/piggy-bank-info/piggy-bank-info.component.ts
> +          const activeCard: Account= JSON.parse(storedCard);
Please remove extra variable here
```suggestion
          const activeCard: Account= JSON.parse(localStorage.getItem('activeCard'));
```

2024-02-28 17:50 UTC, akarmilchik commented on src/app/components/forms/info/piggy-bank-info/piggy-bank-info.component.ts
> +
Please remove extra empty line

2024-02-28 17:50 UTC, akarmilchik commented on src/app/services/payments.service.ts
> +
Please remove extra empty line

2024-02-28 17:50 UTC, akarmilchik commented on src/app/components/user-actions/user-actions.component.ts
> +
Please remove extra empty lines

2024-02-28 17:50 UTC, akarmilchik commented on src/app/components/user-actions/user-actions.component.ts
> +      setTimeout(() => {
Please try to change it to Observable or Subject. Or you can just call it. Why do you need here a setTimeout()?

2024-02-28 17:50 UTC, akarmilchik commented on src/app/components/user-actions/user-actions.component.ts
> +    }
You are setting a lot of things here. It is not clear. Please refactor this functionality. Maybe you can use switch here

2024-03-05 01:14 UTC, LeksoKashia commented on src/app/components/user-actions/user-actions.component.ts
> +      setTimeout(() => {
When adding a new piggy bank, I trigger a function to get updated data from backend to reflect the changes on the website. However, I noticed that the updates weren't appearing immediately, requiring me to wait for the changes to take effect.

2024-03-06 08:00 UTC, akarmilchik approved these changes

2024-03-06 08:42 UTC, merged